name: TF2 GSD

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Every day @ midnight

jobs:
  gsd:
    name: GSD

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout artifacts
        uses: actions/checkout@v3
        with:
          ref: "artifacts-tf2"
          path: "artifacts"

      - name: Install dependencies
        run: | 
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install curl wget file tar bzip2 gzip unzip bsdmainutils cpio distro-info python3 util-linux ca-certificates binutils bc jq tmux netcat lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 libcurl4-gnutls-dev:i386 -y
          
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          
          sudo apt install steamcmd -y

      - name: Install LGSM
        run: wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh tf2server

      - name: Install GS
        run: yes | ./tf2server install

      - name: Install Metamod
        run: echo metamodsource | ./tf2server mods-install

      - name: Install Sourcemod
        run: echo sourcemod | ./tf2server mods-install

      - name: Start server
        run: ./tf2server start

      - name: Wait for server
        run: |
          while ! nc -z localhost 27015; do
            sleep 1
          done

      - name: Dump class list
        run: ./tf2server send "sm_dump_classes classes"

      - name: Dump netprops
        run: |
          ./tf2server send "sm_dump_netprops netprops"
          ./tf2server send "sm_dump_netprops_xml netprops_xml"

      - name: Dump datamaps
        run: |
          ./tf2server send "sm_dump_datamaps datamaps"
          ./tf2server send "sm_dump_datamaps_xml datamaps_xml"

      - name: Aggregate artifacts
        run: |
          cp serverfiles/bin/engine_srv.so artifacts/engine_srv.so
          cp serverfiles/bin/steamclient.so artifacts/steamclient.so
          cp serverfiles/tf/bin/server_srv.so artifacts/server_srv.so

          cp serverfiles/tf/classes artifacts/classes
          cp serverfiles/tf/netprops artifacts/netprops
          cp serverfiles/tf/netprops_xml artifacts/netprops_xml
          cp serverfiles/tf/datamaps artifacts/datamaps
          cp serverfiles/tf/datamaps_xml artifacts/datamaps_xml

          cp serverfiles/tf/scripts/items/items_game.txt artifacts/items_game.txt

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: tf2-binaries
          path: |
            artifacts/engine_srv.so
            artifacts/steamclient.so
            artifacts/server_srv.so

      - name: Upload dumps
        uses: actions/upload-artifact@v3
        with:
          name: tf2-dumps
          path: |
            artifacts/classes
            artifacts/netprops
            artifacts/netprops_xml
            artifacts/datamaps
            artifacts/datamaps_xml

      - name: Upload item script
        uses: actions/upload-artifact@v3
        with:
          name: tf2-item-script
          path: artifacts/items_game.txt

      - name: Commit changes
        working-directory: artifacts
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              git config --global user.name 'rumblefrog'
              git config --global user.email 'contact@rumblefrog.me'
              git add -A
              git commit -m  'chore: artifact upload'
              git push
          fi
